# Generated by Django 2.0.2 on 2018-02-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaultsrv', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('account', 'account_group')},
        ),
    ]
